### PR TITLE
Jake logs(Rev.1)

### PR DESCRIPTION
**Pull request by mavic7**
Ready for code review and discussion before merge

### CODE REVIEW

**Comment by Alex-Programs** [comment]
I like the system you've setup, but I'd like to try to make it more ergonomic by passing a reference to `self` instead of an ID then using https://doc.rust-lang.org/std/any/fn.type_name.html on it to get the module name.

**Comment by Alex-Programs** [comment]
We've also got a conflict on `cargo.lock` - shouldn't that be in the `.gitignore`?

The guidelines are that libs shouldn't check it in, but applications should. This is a library (or at least moreso than an application) and so `cargo.lock` shouldn't be in the VCS. Probably best to wipe it from git history while we're at it - afaik it's not specific to this branch.

**Comment by jw2476** [comment]
It should, for some reason cargo didn't put it there, that's going to be fun to delete

**Comment by mavic7** [comment]
Closing this PR so that I can reopen when suggestions have been implemented, and to try and sort out this weird cargo.lock config issue.

**Pull request closed without merging**
