### PR TITLE
2D Maths

### PR DESCRIPTION
**Pull request by jw2476**
Also sneaking in
- Clock
- Moving examples to birb_examples crate

### CODE REVIEW

**Review by NaughtyDog6000 — APPROVED** [review]
LGTM :)

**Comment by Alex-Programs** [comment]
LGTM!

**Review by mavic7 — DISMISSED** [review]
LGTM.

**Comment by Alex-Programs** [comment]
LBTM - Maths issues

**Comment by mavic7** [comment]
> LBTM - Maths issues

What kind of maths issues?

**Comment by Alex-Programs** [comment]
Jack mentioned issues in the maths IRL without expanding on what exactly - I honestly just wrote here for the meme. "LGTM->LBTM".

**Comment by jw2476** [comment]
Maths should be fixed

**Review by Alex-Programs — APPROVED** [review]
Looks good to me. I've read through it, though I haven't verified the matrix mult etc because frankly I can't remember it.

**Pull request merged**
